# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=250)),
                ('last_name', models.CharField(blank=True, default=None, max_length=250)),
                ('email', models.EmailField(blank=True, default=None, max_length=75, unique=True)),
                ('rate_per_hour', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('contract_exp_date', models.DateField(blank=True, default=None)),
                ('health_book_exp_date', models.DateField(blank=True, default=None)),
            ],
        ),
    ]
