# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_exp_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='health_book_exp_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
