# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 13:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='month_is_approved',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Approved?'),
        ),
        migrations.AlterField(
            model_name='month',
            name='hours_worked_in_this_month',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(720), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=2, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.PositiveIntegerField(default=2017, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
