# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 13:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20161017_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=75, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
