# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 13:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20161018_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=None, max_length=75, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
