# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-13 13:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20170301_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='address_street',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_zip_code',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, validators=[employees.models.zip_check]),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, validators=[employees.models.sanity_check]),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_contact_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='contract exp date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='contract start date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('Fixed-term employment contract', 'Fixed-term employment contract'), ('Non-fixed-term employment contract', 'Non-fixed-term employment contract'), ('Other', 'Other')], default=None, max_length=64, null=True, verbose_name='contract type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=16, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='health_book_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='health book exp date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('Production', 'Production'), ('Sale', 'Sale'), ('Other', 'Other')], default=None, max_length=16, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rate_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='rate per hour'),
        ),
        migrations.AlterField(
            model_name='month',
            name='hours_worked_in_this_month',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(720), django.core.validators.MinValueValidator(0)], verbose_name='hours worked in this month'),
        ),
        migrations.AlterField(
            model_name='month',
            name='rate_per_hour_this_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='rate per hour this month'),
        ),
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.PositiveIntegerField(default=2017, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_city',
            field=models.ForeignKey(blank=True, default=None, max_length=26, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.City'),
        ),
    ]
