# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 10:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20170313_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address_city',
            field=models.ForeignKey(blank=True, default=None, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address_street',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address_zip_code',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, validators=[employees.models.zip_check], verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, validators=[employees.models.sanity_check], verbose_name='Bank account number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_contact_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, validators=[employees.models.phone_check], verbose_name='Phone contact number'),
        ),
        migrations.AlterField(
            model_name='month',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bonuses'),
        ),
    ]
