# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20161207_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hours_in_current_month',
        ),
        migrations.AddField(
            model_name='month',
            name='ordering_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
