# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-28 12:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20161207_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hours_in_current_month',
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('Fixed-term employment contract', 'Fixed-term employment contract'), ('Non-fixed-term employment contract', 'Non-fixed-term employment contract'), ('Other', 'Other')], default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('Production', 'Production'), ('Sale', 'Sale'), ('Other', 'Other')], default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='hours_worked_in_this_month',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(720)]),
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=12, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='month',
            name='rate_per_hour_this_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='month',
            name='salary_is_paid',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Paid?'),
        ),
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.PositiveIntegerField(default=2016, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.RemoveField(
            model_name='month',
            name='how_much_was_paid_to_employee',
        ),
        migrations.AlterUniqueTogether(
            name='month',
            unique_together=set([('employee', 'month', 'year')]),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
