# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 15:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20161215_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='how_much_was_paid_to_employee',
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=12, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.IntegerField(blank=True, default=2016, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
