# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 10:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20161220_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='month',
            name='ordering_field',
        ),
        migrations.AlterField(
            model_name='month',
            name='hours_worked_in_this_month',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(720)]),
        ),
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.PositiveIntegerField(default=2016, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
