# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-26 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20170403_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Production', 'Production'), ('Sale', 'Sale'), ('Other', 'Other')], default='Other', max_length=16, null=True, verbose_name='position'),
        ),
    ]
