# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20161222_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('Fixed-term employment contract', 'Umowa o pracę na czas określony'), ('Non-fixed-term employment contract', 'Umowa-zlecenie'), ('Other', 'Inna')], default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('Production', 'Production'), ('Sale', 'Sale'), ('Other', 'Other')], default=None, max_length=16, null=True),
        ),
    ]
