# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20161222_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('Fixed-term employment contract', 'Fixed-term employment contract'), ('Non-fixed-term employment contract', 'Non-fixed-term employment contract'), ('Other', 'Other')], default=None, max_length=64, null=True),
        ),
    ]
