# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-22 13:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20170427_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=2, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.PositiveIntegerField(default=2018, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year'),
        ),
    ]
