# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_currently_employed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='currently_employed',
            field=models.BooleanField(choices=[(True, 'Current employee'), (False, 'Former employee')], default=True, verbose_name='currently_employed'),
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=3, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='month',
            name='month_is_approved',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, verbose_name='Approved?'),
        ),
    ]
