# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_auto_20180313_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month_is_approved',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, verbose_name='Approved?'),
        ),
    ]
