# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-15 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_month_message_reason_hours_not_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, validators=[employees.models.sanity_check], verbose_name='Bank account number'),
        ),
        migrations.AlterField(
            model_name='month',
            name='message_reason_hours_not_approved',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Comment, why you disagree with the hours (optional)'),
        ),
    ]
