# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-15 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_auto_20180315_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='message_reason_hours_not_approved',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Comment, why you disagree with the hours (optional)'),
        ),
    ]
