version: '3'
services:
  database:
    image: postgres:9.6.2
    volumes:
      - $POLISH_LODY_DATA_DIR:/var/lib/postgresql/data
    restart: on-failure
  web:
    # Custom image, see Dockerfile for base image version
    build: ..
    env_file:
      - .env
    command: gunicorn polishlody.wsgi --workers 2 --bind 0.0.0.0:8000
    depends_on:
      - database
    expose:
      - "8000"
    restart: on-failure
  nginx:
    build: ../nginx/
    ports:
      - $POLISH_LODY_PORT:80
    depends_on:
      - web
    restart: on-failure