version: '3'
services:
  database:
    image: postgres
    volumes:
      - $POLISH_LODY_DATA_DIR/database:/var/lib/postgresql/data
    restart: on-failure
  web:
    build: ..
    command: gunicorn polishlody.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:$POLISH_LODY_PORT
    depends_on:
      - database
    environment:
      - EMAIL_HOST=
      - EMAIL_HOST_PASSWORD=
      - EMAIL_HOST_USER=
      - WEATHER_API_KEY=
      - SECRET_KEY
      - POLISH_LODY_DATABASE
    restart: on-failure
