version: '3'
services:
  database:
    build:
      context: ../
      dockerfile: deployment/database-dockerfile/Dockerfile
    volumes:
      - $POLISH_LODY_DATA_DIR/database:/var/lib/postgresql/data
    restart: on-failure
  web:
    # Custom image, see Dockerfile for base image version
    build:
      context: ../
      dockerfile: deployment/web-dockerfile/Dockerfile
    command: gunicorn polishlody.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:$POLISH_LODY_PORT
    depends_on:
      - database
    environment:
      - EMAIL_HOST=
      - EMAIL_HOST_PASSWORD=
      - EMAIL_HOST_USER=
      - WEATHER_API_KEY=
      - SECRET_KEY
      - POLISH_LODY_DATABASE
    restart: on-failure
