- hosts: "{{ hosts }}"
  vars_files:
    - vars.yaml
    - "./secrets/{{ instance_name }}-secrets.yaml"
    - "{{ instance_name }}-vars.yaml"

  tasks:
    - become: yes
      become_user: "{{ user }}"
      block:

        - name: drop database
          command: "docker-compose --project-name {{ instance_name}} run --rm database dropdb polishlody --user postgres --host database"
          args:
            chdir: "{{ app_dir }}/deployment/"