- hosts: "{{ hosts }}"
  vars_files:
  - vars.yaml
  - secrets.yaml
  - "{{ instance_name }}-vars.yaml"

  tasks:
    - become: yes
      become_user: "{{ user }}"
      block:

        - name: run docker-compose build
          command: docker-compose run --rm database dropdb polishlody --user postgres --host database
          args:
            chdir: "{{ app_dir }}/deployment/"