- hosts: "{{ hosts }}"
  vars_files:
    - vars.yaml
    - "./secrets/{{ instance_name }}-secrets.yaml"
    - "{{ instance_name }}-vars.yaml"

  tasks:
    - become: yes
      become_user: "{{ user }}"
      block:

        - name: create database
          command: "docker-compose --project-name {{ instance_name }} run --rm database createdb polishlody --user postgres --host database"
          args:
            chdir: "{{ app_dir }}/deployment/"

        - name: run database migration
          command: "docker-compose --project-name {{ instance_name }} run --rm web ./manage.py migrate"
          args:
            chdir: "{{ app_dir }}/deployment/"

        - name: load data to database
          command: "docker-compose --project-name {{ instance_name }} run --rm web ./manage.py loaddata /code/employees/fixtures/fikstura_cities.json"
          args:
            chdir: "{{ app_dir }}/deployment/"