- hosts: "{{ hosts }}"
  vars_files:
    - vars.yaml
    - "./secrets/{{ instance_name }}-secrets.yaml"
    - "{{ instance_name }}-vars.yaml"

  tasks:
    - become: yes
      become_user: "{{ user }}"
      block:
        - name: run docker-compose down
          command: "docker-compose --project-name {{ instance_name }} down"
          args:
            chdir: "{{ app_dir }}/deployment/"